[package]
name = "example_derive"
version = "0.0.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
derive_utils = { path = "../.." }
syn = { version = "1.0" }
